[package]
name = "cv"
version = "0.1.0"
authors = ["hmziqrs <hmziqrs@gmail.com>"]
edition = "2024"

[dependencies]
chrono = "0.4.44"
dioxus = { version = "0.7.9", features = ["router", "fullstack"] }
hmziq-dioxus-free-icons = { version = "0.10.1", features = [
    "simple-icons",
    "lucide",
] }
serde_json = "1.0.149"
askama_escape = { version = "0.16.0", optional = true }

[dev-dependencies]
headless_chrome = { git = "https://github.com/rust-headless-chrome/rust-headless-chrome", features = [
    "fetch",
] }

[features]
default = ["web"]
web = ["dioxus/web"]
desktop = ["dioxus/desktop"]
mobile = ["dioxus/mobile"]
server = ["dioxus/server", "dep:askama_escape"]

[profile]

[profile.wasm-dev]
inherits = "dev"
opt-level = 1

[profile.release]
opt-level = "z"
debug = false
lto = true
codegen-units = 1
panic = "abort"
strip = true
incremental = false


[profile.server-dev]
inherits = "dev"

[profile.android-dev]
inherits = "dev"

[[bin]]
name = "stripper"
path = "scripts/stripper.rs"

[[bin]]
name = "chrome_capture"
path = "scripts/chrome_capture.rs"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
headless_chrome = { git = "https://github.com/rust-headless-chrome/rust-headless-chrome", features = [
    "fetch",
] }
axum = "0.8.9"
tokio = { version = "1.52.3", features = ["full"] }
tower-http = { version = "0.6.10", features = ["fs"] }
scraper = "0.27.0"
cargo_toml = "0.22.3"
regex = "1.12.3"
kuchikiki = "0.8.8-speedreader"
minify-html = "0.18.1"
lightningcss = { version = "1.0.0-alpha.71", features = ["serde"] }
