# Sample workflow for building and deploying a Next.js site to GitHub Pages
#
# To get started with Next.js see: https://nextjs.org/docs/getting-started
#
name: Deploy Next.js site to Pages

on:
  push:
    branches: ["master"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - name: Setup Pages
        uses: actions/configure-pages@v5
        with:
          static_site_generator: next
      - name: Install playwright
        run: bunx playwright install chromium
      - name: Install dependencies
        run: bun i
      - name: Next.JS export
        run: bun run build
      - run: ls out
      - name: Take CV snapshots
        run: bun cv-local
      - name: Next.JS export post cv
        run: bun run build
      - uses: actions/upload-artifact@v4
        with:
          name: "hmziqrs-dark-cv.jpg"
          path: "public/hmziqrs-dark-cv.jpg"
      - uses: actions/upload-artifact@v4
        with:
          name: "hmziqrs-dark-cv.pdf"
          path: "public/hmziqrs-dark-cv.pdf"
      - uses: actions/upload-artifact@v4
        with:
          name: "hmziqrs-light-cv.jpg"
          path: "public/hmziqrs-light-cv.jpg"
      - uses: actions/upload-artifact@v4
        with:
          name: "hmziqrs-light-cv.pdf"
          path: "public/hmziqrs-light-cv.pdf"
      # - run: bun i wrangler -g
      # - name: wrangler publish
      #   run: $ CLOUDFLARE_ACCOUNT_ID=<ACCOUNT_ID> bunx wrangler pages deploy ./out --project-name=<PROJECT_NAME>
      - name: Publish
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: "hmziqrs-cv"
          directory: "out"
          gitHubToken: ${{ secrets.TOKEN }}

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
