name: Test Binary Execution

on:
  push:
    paths:
      - '.github/workflows/test.yml'
  workflow_dispatch:

jobs:
  test-execution:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create bin directory
        run: mkdir -p ./bin

      # Instead of downloading from GitHub release, use the existing debug binaries
      - name: Copy local debug stripper binary
        run: |
          # Build the binaries directly instead of downloading them
          cargo build --bin stripper
          cargo build --bin chrome_capture

          # Copy to bin directory
          cp ./target/debug/stripper ./bin/stripper
          cp ./target/debug/chrome_capture ./bin/chrome_capture

          # Make sure they're executable
          chmod +x ./bin/stripper
          chmod +x ./bin/chrome_capture

          # Verify binaries
          ls -la ./bin/
          file ./bin/stripper
          file ./bin/chrome_capture

      - name: Test execution
        run: |
          echo "Testing stripper execution:"
          ./bin/stripper --help || echo "Exit code: $?"

          echo "Testing chrome_capture execution:"
          ./bin/chrome_capture --help || echo "Exit code: $?"

